---
title: "BA Project1 Noraml Dist"
author: "Yichun Zhou"
date: "2/14/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r clean date}
library(readxl)
setwd("/Users/joezhou/Desktop/2020 Spring/BA/project1")
data <- read_excel ("clean_data.xlsx")
summary(data)
mean <- mean(data$Grade)
sd <- sd(data$Grade)
quantile <-quantile(data$Grade)
mean
sd
quantile
```

## Including Plots

You can also embed plots, for example:

```{r histogram}
library(ggplot2)
ggplot(data, aes(x=Grade)) + geom_histogram(binwidth = 1,color="white", fill="lightblue") + 
  ylab('Count') + 
  ggtitle('Student Quiz Grade Histogram') + theme(plot.title = element_text(hjust = 0.5,size = 20))


```
```{r Number of Observation in the data }
print('H0: the Student Quiz Grade dataset follows the normal distribution')
print('H1: the Student Quiz Grade dataset does not follow the normal distribution')

#A matrix to store the information for Chi_square
chi_matrix <- matrix(c(0,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,10),nrow=10,ncol=6)
chi_matrix[1,3] <- length(which(data >=0 & data <=1))

for (i in 2:10){
  chi_matrix[i,3] <- length(which(data > i-1 & data <= i))
}

chi_matrix[,3]

hist.df <- as.data.frame(chi_matrix)
#hist.df[2]
count = hist.df[3]
#geom_bar(mapping = NULL, data = NULL, stat = "count",
#  position = "stack", ..., width = NULL, binwidth = NULL,
#  na.rm = FALSE, show.legend = NA, inherit.aes = TRUE)

#ggplot(hist.df, aes(x=V2, y=V3)) + geom_bar(stat="identity",color="white", fill="lightblue") + 
#  ylab('Count') + xlab('Grade')+
#  ggtitle('Student Quiz Grade Histogram') + theme(plot.title = element_text(hjust = 0.5,size = 20))

```
```{r Class probability} 
#data1 = table(data$Grade)
#data1
chi_matrix[1,4] <- (1 - pnorm(chi_matrix[1,2], mean, sd,lower.tail = FALSE))
for (i in 2:9){
  chi_matrix[i,4] <- (1 - pnorm(chi_matrix[i,2], mean, sd,lower.tail = FALSE) -( 1- pnorm(chi_matrix[i-1,2], mean, sd,lower.tail = FALSE)))
}
chi_matrix[10,4] <- pnorm(chi_matrix[9,2], mean, sd,lower.tail = FALSE)

chi_matrix[,4]
```
```{r Expected Value}
for (i in 1:10){
  chi_matrix[i,5] <- length(data$Grade) * (chi_matrix[i,4])
}
chi_matrix[,5] 
```
```{r}
for (i in 1:10){
  chi_matrix[i,6] <- ((chi_matrix[i,3] -chi_matrix[i,5] )**2)/chi_matrix[i,5] 
}
chi_matrix[,6]

Chi_square_value <- sum(chi_matrix[,6])
Chi_square_value

Test_statistics <- qchisq(.95, length(chi_matrix[,1])-1)
Test_statistics

print ('Chi_square_value < Test_statistics, Fail to reject H0. And this dataset follows normal distribution.')
```

